for file in ~/.{aliases,functions,exports,extras,tokens}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

. "$HOME/.cargo/env"

addToPath "$HOME/.console-ninja/.bin"
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# assumes a global install of ghapi
# eval "$(completion-ghapi --install)"

export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# Added by LM Studio CLI (lms)
if [ -d "$HOME/.cache/lm-studio/bin" ]; then
    export PATH="$PATH:$HOME/.cache/lm-studio/bin"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f "$HOME/.ghcup/env" ] && . "$HOME/.ghcup/env" # ghcup-env

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

path=("$HOME/.juliaup/bin" $path)
export PATH

# <<< juliaup initialize <<<

# direnv
eval "$(direnv hook zsh)"

# add code to path (macOS)
if [ -d "/Applications/Visual Studio Code.app/Contents/Resources/app/bin" ]; then
    addToPath "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
fi
